version = 0.1
[default.deploy.parameters]
stack_name = "hubermangpt-app"
resolve_s3 = true
s3_prefix = "hubermangpt-app"
region = "us-west-1"
profile = "my-dev-profile"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["FastAPIFunction=986851011610.dkr.ecr.us-west-1.amazonaws.com/hubermangptappbff9d341/fastapifunctionead79d0drepo"]
